name: "@kessix_"
description: sysadmin explorando o mundo DevOps e Cloud Computing
meta_description: "Jekyll Blog's"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://kessix.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "kessix"

# Disqus config
disqus-shortname: ""
